apiVersion: apps/v1
kind: Deployment
metadata:
  name: yy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yy
  template:
    metadata:
      labels:
        app: yy
    spec:
      containers:
      - image: okteto.dev/yy:latest
        name: yy
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "3bc3fb88-1e4c-415a-8bdd-c027068b0819"
        - name: Vless_Path
          value: "/vl555"
        - name: Vmess_UUID
          value: "3bc3fb88-1e4c-415a-8bdd-c027068b0819"
        - name: Vmess_Path
          value: "/vm666"
        - name: Share_Path
          value: "/v2link"
